# 
# Author        : Summer
# Description   : Make a short description for your file
# 
# Revision      : 
# Rev.    Date        Designer    Description
# 1.0     2023-11-07  Summer      Initial version
# 1.1     2023-01-17  Summer      configure_prompt
# 

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

source $SUMMER_CONFIG_DIR/common/alias.sh
source $SUMMER_CONFIG_DIR/common/clangd.sh
source $SUMMER_CONFIG_DIR/common/git.sh

source ${SUMMER_CONFIG_DIR}/bash_setting/config/bash_prompt.sh

source ${SUMMER_CONFIG_DIR}/bash_setting/plugin/ble-0.4.0-devel3/ble.sh
